In [4]:
from main import *
path_df_ocorrencias = Path("main.py").parent / "dados" / "ocorrencias.json"
df_ocorrencias = pd.read_json(path_df_ocorrencias)
pd.set_option("display.expand_frame_repr", False)

In [5]:
df_ocorrencias["data"] = pd.to_datetime(df_ocorrencias["data"], format="%d/%m/%Y %H:%M:%S")
display(df_ocorrencias[df_ocorrencias["tipo"] == "Roubo"])
display(df_ocorrencias["tipo"].describe())
display(df_ocorrencias[df_ocorrencias["tipo"] == "Roubo"][["descricao","data"]])

    Id   tipo                 local                descricao                data        status
0    1  Roubo                   NaN                    teste 2022-05-19 11:04:42  Em andamento
5    6  Roubo       Mercado Popular         Roubo de celular 2025-01-18 15:34:18  Em andamento
9   10  Roubo   Terminal Rodoviário         Roubo de mochila 2020-02-09 21:56:40      Pendente
13  14  Roubo  Posto de Combustível         Assalto ao caixa 2025-02-28 23:47:36  Em andamento
17  18  Roubo     Rua das Palmeiras     Roubo de motocicleta 2020-03-21 18:05:12     Concluído
22  23  Roubo        Banco Regional     Tentativa de assalto 2020-04-16 05:22:49      Pendente
27  28  Roubo      Farmácia Central  Assalto com arma branca 2025-05-07 10:31:47  Em andamento

count        31
unique        8
top       Roubo
freq          7
Name: tipo, dtype: object

                  descricao                data
0                     teste 2022-05-19 11:04:42
5          Roubo de celular 2025-01-18 15:34:18
9          Roubo de mochila 2020-02-09 21:56:40
13         Assalto ao caixa 2025-02-28 23:47:36
17     Roubo de motocicleta 2020-03-21 18:05:12
22     Tentativa de assalto 2020-04-16 05:22:49
27  Assalto com arma branca 2025-05-07 10:31:47

In [6]:
display(df_ocorrencias.info())

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         31 non-null     int64
 1   tipo       31 non-null     str
 2   local      30 non-null     str
 3   descricao  31 non-null     str
 4   data       31 non-null     datetime64[us]
 5   status     31 non-null     str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 1.6 KB

None